### ISSUE TITLE
Verifica delle modalità di garbage collection dei dati di sessione memorizzati in DB

### ISSUE THREAD

**Issue by pdavide** [pdavide/wai-infrastructure#108]
A valle della prima scansione di sicurezza, nella tabella `session` di matomo erano memorizzate circa 600k righe. Andrebbe verificata, se esiste, quale modalità di garbage collection di questi dati è prevista da matomo.

**Comment by Valair** [comment]
Il [`dbtable` session handler](https://github.com/matomo-org/matomo/blob/3.x-dev/core/Session/SaveHandler/DbTable.php) di matomo è lo stesso di `Zend_Session` handler.
Il cleanup della tabella `session` è affidato al al [Garbage Collector](https://github.com/matomo-org/matomo/blob/be5a28b35a8e3dcaeb3ade78fd02ecb2a08cd3d1/core/Session/SaveHandler/DbTable.php#L173) passato il `modified+lifetime` (dove `lifetime` corrisponde al valore `session.gc_maxlifetime`)
Matomo personalizza alcuni valori di php.ini in [Session](https://github.com/matomo-org/matomo/blob/3.x-dev/core/Session.php), nel dettaglio:
- `session.gc_maxlifetime` corrisponde a `login_cookie_expire` (default 14 giorni), configurabile nella sesione `General` 
- `session.gc_probability` forzata a `1`
