### ISSUE TITLE
Aggiornamento DB GeoIP

### ISSUE THREAD

**Issue by pdavide** [pdavide/wai-infrastructure#128]
Riporto la discussione a proposito di questa issue dalla PR https://github.com/pdavide/wai-portal/pull/463#issuecomment-575700279_.

> Considerato anche che il Pod che esegue il `cron:archive` è un "worker" temporaneo (@giafar), a livello di filesystem sui Pod non si aggiornerà nulla. Abbiamo due strade per il db geo IP:
> 
> * aggiornare l'immagine di matomo una volta al mese, magari introducendo un automatismo (su DB-IP vedo che la schedulazione è ogni [primo giorno del mese](https://db-ip.com/faq.php#Q_General_e404c493)
> * modificare il "worker" ed i Pod di matomo in modo che il db geo ip locale sia un link ad un file su un volume condiviso (non tutta la folder `misc`) ed invece del semplice `cron:archive`, il worker esegue uno script che aggiorna il file condiviso
> 
> Con la lista attuale di plugin, mi sembra che l'unico altro task ad agire sul filesystem sia quello di [CustomPiwiJs](https://github.com/matomo-org/matomo/blob/3.x-dev/plugins/CustomPiwikJs/TrackerUpdater.php), ma non abbiamo personalizzazioni attive in merito.

Io propenderei per la soluzione numero 2 con lo stesso volume montato in rw per il pod del CronJob che esegue `cron:archive` e montato poi in sola lettura su tutti i pod di matomo (portale, ingestion, etc.).

Direi comunque di aprire una issue *ad hoc* e liberare questa PR.

@giafar tu che ne pensi?

**Comment by giafar** [comment]
@pdavide concordo per la soluzione 2

**Comment by pdavide** [comment]
Closed in #138.
