### ISSUE TITLE
Codice non usato?

### ISSUE THREAD

**Issue by pdavide** [pdavide/wai-infrastructure#142]
Sembra che il codice in:
https://github.com/pdavide/wai-infrastructure/blob/06100a437168a4918d8ef763a324573173d63bac/playbooks/templates/k8s/jail/matomo-jail.yml.j2#L264-L268 non venga mai usato.

È effettivamente inutile oppure c'è un errore nei valori delle variabili che lo attivano?
https://github.com/pdavide/wai-infrastructure/blob/06100a437168a4918d8ef763a324573173d63bac/playbooks/k8s-templates.yml#L70-L71

**Comment by giafar** [comment]
Hai ragione.
Credo lo usassimo prima di fare l'ingress con il *capture group* per /matomo. In realtà l'ultimo template non creando l'ingress non attiva quel pezzo di codice.

**Comment by pdavide** [comment]
Closed in #143.
