### ISSUE TITLE
Header CSP

### ISSUE THREAD

**Issue by pdavide** [pdavide/wai-infrastructure#221]
@giafar l'header definito in
https://github.com/AgID/wai-infrastructure/blob/c7f2b759258f81d5682c13d819b5ee458173f0f2/playbooks/templates/k8s/jail/matomo-jail.yml.j2#L155
viene sostituito da quello impostato nello script lua oppure diventa un duplicato?

**Comment by giafar** [comment]
> @giafar l'header definito in
> https://github.com/AgID/wai-infrastructure/blob/c7f2b759258f81d5682c13d819b5ee458173f0f2/playbooks/templates/k8s/jail/matomo-jail.yml.j2#L155
> 
> 
> viene sostituito da quello impostato nello script lua oppure diventa un duplicato?

Dovrebbe essere sostituito ma in giornata faccio un test e ti do risposta qui

**Comment by giafar** [comment]
La tua osservazione era corretta: fatta commit 355c7ce099b7dc9e8ed042fa3cf1a34437dd6c54 e relativa PR #222 che hai già approvato :-P

**Comment by pdavide** [comment]
Closed in #222.
