### ISSUE TITLE
Storage persistente per portal

### ISSUE THREAD

**Issue by pdavide** [pdavide/wai-infrastructure#232]
Servirebbe un volume persistente da montare in RW in tutti i pod che hanno immagine `wai-portal`, che sono `portal`, `portal-queue-worker` e `portal-scheduler` (quest'ultimo al momento attivo solo in ambiente play).
Il volume va montato in `/var/www/html/storage/persistent` e la directory deve essere scrivibile (755) dall'utente `www-data` del pod.
Come dimensione dovrebbero andare benissimo 2GB.
Non è necessario creare il volume anche in ambiente stag (quindi solo play e prod).

**Comment by giafar** [comment]
@pdavide se dobbiamo metterla anche nel repo credi sia possibile fare questa configurazione anche per stag in modo da non "complicare" il playbook ?

**Comment by pdavide** [comment]
Si certo!

**Comment by pdavide** [comment]
Closed in #233.

**Comment by pdavide** [comment]
@giafar 
La directory `/var/www/html/storage/persistent` non risulta scrivibile dall'utente www-data:
```bash
drwxrwsr-x 3 root         2014 4096 Feb 16 07:09 persistent
```
Si deve sistemare qualcosa nelle opzioni di mount oppure è necessario avere la directory già creata nel pod prima del mount?

**Comment by giafar** [comment]
@pdavide tra oggi e domani la verifichiamo anche se il fsGroup del securityContext del POD è 33 quindi il gruppo deve poter scrivere.

**Comment by pdavide** [comment]
> @pdavide tra oggi e domani la verifichiamo anche se il fsGroup del securityContext del POD è 33 quindi il gruppo deve poter scrivere.

Ok grazie, ti chiedo di risolvere il prima possibile perché per me è bloccante rispetto all'invio delle statistiche SDG.
Se può essere d'aiuto, nell'output che ti ho incollato da play il `gid` della dir montata è `2014` mentre in stag è `2000`.

Per provare uso:
```bash
sudo -u www-data touch /var/www/html/storage/persistent/test
> touch: cannot touch '/var/www/html/storage/persistent/test': Permission denied
```

**Comment by pdavide** [comment]
Data la modifica in #237, secondo te possiamo eliminare i securityContext introdotti nella #233?
