### ISSUE TITLE
Ottimizzazione check request

### ISSUE THREAD

**Issue by pdavide** [pdavide/wai-infrastructure#271]
@giafar che ne pensi se questo controllo lo anticipiamo prima della connessione a redis? Non ci risparmierebbe un po' di lavoro in meno in caso di risposta 401?

https://github.com/AgID/wai-infrastructure/blob/43cf2bc319fd935ac49650db1101e5df77e08609/images/wai-openresty/wai-csp.lua#L44-L46

**Comment by giafar** [comment]
> @giafar che ne pensi se questo controllo lo anticipiamo prima della connessione a redis? Non ci risparmierebbe un po' di lavoro in meno in caso di risposta 401?
> 
> https://github.com/AgID/wai-infrastructure/blob/43cf2bc319fd935ac49650db1101e5df77e08609/images/wai-openresty/wai-csp.lua#L44-L46

Decisamente, lo portiamo sopra, creo la ISSUE
