### ISSUE TITLE
Servizio di raccolta statistiche non più funzionante

### ISSUE THREAD

**Issue by stefanoel** [pdavide/wai-infrastructure#311]
Ciao, da circa 2 mesi il servizio non raccoglie più dati sull'utilizzo del nostro sito web.
Ad esempio dalla home page viene richiamato 

https://ingestion.webanalytics.italia.it/matomo.php?action_name=Home%20-%20Universit%C3%A0%20degli%20Studi%20di%20Perugia&idsite=XkJ3Zjy3Ly&rec=1&r=219154&h=15&m=57&s=58&url=https%3A%2F%2Fwww.unipg.it%2F&urlref=https%3A%2F%2Fwww.unipg.it%2Fcontatti%2Frubrica&_id=99d1294aef8bb3b4&_idts=1662640488&_idvc=1&_idn=0&_refts=0&_viewts=1662640488&send_image=1&cookie=1&res=1280x1024&gt_ms=560&pv_id=egXo4f

che restituisce errore 500 e analogamente per tutte le altre pagine del sito web.

Ce ne siamo accorti ora ma utilizziamo il servizio da oltre un anno e ha sempre funzionato fino al 13 luglio 2022, ultimo giorno per cui sono disponibili le statistiche nella dashboard.

**Comment by pdavide** [comment]
## Comunicazione importante

https://webanalytics.italia.it/#comunicazione-potenziamento.
