### ISSUE TITLE
Emissione certificati per OpenVPN e file di configurazione

### ISSUE THREAD

**Issue by giafar** [pdavide/wai-infrastructure#76]
Per l'emissione di un certificato per il server VPN è necessario per prima cosa creare una chiave privata con il comando `openssl genrsa -out <utente>.key 4096` e successivamente creare una *Certificate signing request* tramite con il comando `openssl req -new -key <utente>.key -nodes -out <utente>.csr -subj '/CN=<utente>/O=<organizzazione>'`. 

Il parametro *utente* rappresenta l'utente che richiede l'accesso al sistema mentre il parametro *organizzazione* l'azienda per cui lavoro l'utente.

L'operazione da eseguire lato server vpn è quella di firmare la *csr* con il certificato e la chiave privata della certification authority di Web Analytics Italia ovvero è necessario eseguire il comando `openssl ca -config wai-operation-root-ca.conf -out <utente>.crt -infiles <utente>.csr`.

Ricevuto il certificato è possibile creare il file di configurazione secondo il modello di seguito riportato:
```
client
dev tun
proto tcp
remote <ip server vpn> 443
resolv-retry infinite
nobind
persist-key
persist-tun
verb 11
keepalive 10 900
inactive 3600
comp-lzo
<cert>
INCOLLARE IL CONTENUTO DEL CERTIFICATO
</cert>
<key>
INCOLLARE IL CONTENUTO DELLA CHIAVE PRIVATA
</key>
<ca>
INCOLLARE IL CONTENUTO DEL CERTIFICATO DELLA CA
</ca>
```

**Comment by pdavide** [comment]
Copiate info nella wiki del repo.
