### ISSUE TITLE
Emissione certificato per accesso Kubernetes

### ISSUE THREAD

**Issue by giafar** [pdavide/wai-infrastructure#77]
Per l'emissione di un certificato per il server VPN è necessario per prima cosa creare una chiave privata con il comando `openssl genrsa -out <utente>.key 4096` e successivamente creare una Certificate signing request tramite con il comando `openssl req -new -key <utente>.key -nodes -out <utente>.csr -subj '/CN=<utente>/O=<organizzazione>'`.

Il parametro utente rappresenta l'utente che richiede l'accesso al sistema mentre il parametro organizzazione l'azienda per cui lavoro l'utente.

Lato kubernetes sarà necessario  caricare la csr con il seguente comando. 
```bash
$ cat <<EOF | kubectl apply -f -
apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: <utente>
spec:
  request: $(cat <utente>.csr | base64 | tr -d '\n')
  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth
EOF
```
per poi approvarla con il comando `kubectl certificate approve <utente>` e salvare quindi il certificato con il comando `kubectl get csr <utente> -o jsonpath={.status.certificate} | base64 --decode > <utente>.crt`.

Ricevuto il certificato ed il certifiato della CA di Kubernetes è possibile definire la configurazione con i comandi:
```bash
$ kubectl config set-credentials <utente>-wai --client-certificate=<utente>.crt --client-key=<utente>.key --embed-certs
$ kubectl config set-cluster wai --server=https://<ip api server>:<porta api server> --certificate-authority=wai.crt  --embed-certs
$ kubectl config set-context <utente>-wai --cluster=wai --user=<utente>-wai
```

Creata la configurazione è possibile attivarla con il comando `kubectl config use-context <utente>-wai`

**Comment by pdavide** [comment]
Informazioni riportate nella wiki.
